//-----------------------------------------------------------------------
// <copyright file="MBook.cs" company="517 Enterprises">
//      Copyright (c) 517 Enterprises. All rights reserved.
// </copyright>
// <date>2014/2/22 11:45:36</date>
// <Author>auto generated by .xla</Author>
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace Personnel.Amy.Model
{
    /// <summary>
    /// 图书表
    /// </summary>
    [DataContract]
    public class MBook
    {
        #region private members

        /// <summary>
        ///  主键ID
        /// </summary>
        private string keyID = string.Empty;

        /// <summary>
        ///  书名
        /// </summary>
        private string name = string.Empty;

        /// <summary>
        ///  作者
        /// </summary>
        private string author = string.Empty;

        /// <summary>
        ///  出版社
        /// </summary>
        private int press;

        /// <summary>
        ///  出版日期
        /// </summary>
        private DateTime pressDateTime;

        /// <summary>
        ///  是否已读
        /// </summary>
        private int isRead;

        /// <summary>
        ///  是否删除
        /// </summary>
        private int isDelete;

        #endregion

        #region construction

        /// <summary>
        /// 构造函数
        /// </summary>
        public MBook()
        {
        }

        #endregion

        #region public members

        /// <summary>
        /// 主键ID
        /// </summary>
        [DataMember]
        public string KeyID
        {
            get { return this.keyID; }
            set { this.keyID = value; }
        }

        /// <summary>
        /// 书名
        /// </summary>
        [DataMember]
        public string Name
        {
            get { return this.name; }
            set { this.name = value; }
        }

        /// <summary>
        /// 作者
        /// </summary>
        [DataMember]
        public string Author
        {
            get { return this.author; }
            set { this.author = value; }
        }

        /// <summary>
        /// 出版社
        /// </summary>
        [DataMember]
        public int Press
        {
            get { return this.press; }
            set { this.press = value; }
        }

        /// <summary>
        /// 出版日期
        /// </summary>
        [DataMember]
        public DateTime PressDateTime
        {
            get { return this.pressDateTime; }
            set { this.pressDateTime = value; }
        }

        /// <summary>
        /// 是否已读
        /// </summary>
        [DataMember]
        public int IsRead
        {
            get { return this.isRead; }
            set { this.isRead = value; }
        }

        /// <summary>
        /// 是否删除
        /// </summary>
        [DataMember]
        public int IsDelete
        {
            get { return this.isDelete; }
            set { this.isDelete = value; }
        }

        #endregion

    }
}